# Generated by Django 5.2.7 on 2025-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('IN', 'Individual'), ('CO', 'Company'), ('ST', 'Student'), ('NP', 'Non-Profit')], default='IN', max_length=2, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
